version: "3.9"
services:
  bitcoin:
    container_name: bitcoin
    image: ruimarinho/bitcoin-core:latest
    command: -printtoconsole -blocksonly -prune=550 -maxmempool=5 -maxconnections=5 -rpcport=8322
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 8322:8322
    volumes:
      - ./bitcoin.conf:/root/.bitcoin/bitcoin.conf
      - ./bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf
      - bitcoin:/home/bitcoin/.bitcoin
    networks:
      - rollo
      - shared
  # ethereum:
  #   container_name: ethereum
  #   image: ethereum/client-go:stable
  #   command: --syncmode light --http
  #   restart: always
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ethereum:/root/.ethereum
  #   ports:
  #     - 8545:8545
networks:
  rollo:
    driver: bridge
  shared:
    external: true
volumes:
  bitcoin:
  # ethereum:
