version: "3.9"
services:
  bitcoin:
    image: ruimarinho/bitcoin-core:latest
    container_name: rollo_bitcoin
    hostname: rollo_bitcoin
    command: -printtoconsole -blocksonly -prune=550 -maxmempool=5 -maxconnections=5 -rpcport=8322
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./bitcoin.conf:/root/.bitcoin/bitcoin.conf
      - ./bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf
      - bitcoin:/home/bitcoin/.bitcoin
    networks:
      - rollo
      - shared
  ethereum:
    image: ethereum/client-go:stable
    container_name: rollo_ethereum
    hostname: rollo_ethereum
    command: --syncmode light --http
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ethereum:/root/.ethereum
    networks:
      - rollo
      - shared
networks:
  rollo:
    driver: bridge
  shared:
    external: true
volumes:
  bitcoin:
  ethereum:
